/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py:51: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if argname is not '':
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/train.py", line 15, in <module>
    from utils.misc import AverageMeter, prep_experiment, evaluate_eval, fast_hist, set_bn_eval
  File "/home/heonsung/Desktop/Segmentation/SFSegNets/utils/misc.py", line 12, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2461702) of binary: /home/heonsung/miniconda3/envs/lab/bin/python
Traceback (most recent call last):
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/heonsung/miniconda3/envs/lab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2461703)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2461704)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2461705)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2461706)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 2461707)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 2461708)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 2461709)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-15_22:49:40
  host      : cal-05
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2461702)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
